name: "Deploy Cloud Functions"
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  job_id:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/243936487164/locations/global/workloadIdentityPools/github-pool/providers/github-pool'
        service_account: 'wif-service@hive-flora.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0.10.0'
      with:
        name: 'notify_low_balance'
        env_vars: EMAIL_FROM_DEFAULT=${{ secrets.EMAIL_FROM_DEFAULT }}, POSTMARK_SERVER_API_TOKEN=${{ secrets.POSTMARK_SERVER_API_TOKEN }}, EMAIL_TO_DEFAULT=${{ secrets.EMAIL_TO_DEFAULT }}
        runtime: 'nodejs16'
        timeout: 300
        deploy_timeout: 300

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'


  # build:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - run: gcloud functions deploy notify_low_balance --entry-point notify_low_balance --runtime nodejs16 --trigger-http --allow-unauthenticated --set-env-vars EMAIL_FROM_DEFAULT=${{ secrets.EMAIL_FROM_DEFAULT }}, POSTMARK_SERVER_API_TOKEN=${{ secrets.POSTMARK_SERVER_API_TOKEN }}, EMAIL_TO_DEFAULT=${{ secrets.EMAIL_TO_DEFAULT }}
